### ISSUE TITLE
Feature request: Add select window closing

### ISSUE THREAD

**Issue by DEliasVCruz** [ten3roberts/window-picker.nvim#6]
It would be nice if as you can pick windows you could integrate some way of closing them. The same interface, just that instead of picking or swapping it close the selected window.

**Comment by ten3roberts** [comment]
That would be kind of cool to have.

The plugin is quite easy to extend so I could easily add that, as well as maybe adding a public facing "callback based" api for doing anything you want with the selected window, similar to vim.ui.select api.

**Comment by ten3roberts** [comment]
I have implemented the functionality, as well as made WindowPick zap if alt is held, similar to how it is swapped with shift.

A select api is also exported which allows you to define other functionality.

Let me know what you think

**Comment by DEliasVCruz** [comment]
This is great!!! Thank you so very much. The only thing is that after selecting a window to close it prompts for `<Enter>` input or any other `key` to complete the action. I don't know if this is intentional or if is a bug.

I've yet to test the select api

**Comment by ten3roberts** [comment]
That sounds like vim prompting because there are more things in the cmdline, which happens if a number of consecutive messages exceed `cmdheight`

What is your `cmdheight` set to, and what si the output of `:messages` after the bug?

**Comment by DEliasVCruz** [comment]
That is certainly odd. My `cmdheight` is set to `1` and the output of `:messages` is:

```
Zap window:

Pulse INTRO o escriba una orden para continuar
```

The final message roughly translates to: `Press ENTER or write a command to continue`

**Comment by DEliasVCruz** [comment]
The latest commit seems to have solved the issue. Thanks!
